name: 'dotcover-reporters'
description: 'Reports cover output.'
inputs:
  name:
    description: "-Name check run-"
    required: true
    default: 'Test Coverage'
  path:
    description: "-Path to output-"
    required: true
    default: ''
  version:
    description: "The client version."
    required: false
    default: '0.0.0-preview.0'
  token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
